### ISSUE TITLE
Boolean value subbands in istft_vits2_base.json?

### ISSUE THREAD

**Issue by isdanni** [FENRlR/MB-iSTFT-VITS2#14]
https://github.com/FENRlR/MB-iSTFT-VITS2/blob/17593f65ae3cfa99fa584c1e4e1d5723e2a4d97d/configs/istft_vits2_base.json#L51
vs 

https://github.com/FENRlR/MB-iSTFT-VITS2/blob/17593f65ae3cfa99fa584c1e4e1d5723e2a4d97d/pqmf.py#L56

Was wondering if this is accurate? I usually see people set it to values like 4 or 8

**Comment by FENRlR** [comment]
It was the original [MB-iSTFT-VITS repository](https://github.com/MasayaKawamura/MB-iSTFT-VITS) which set it to the boolean type, but that does not really matter because the [istft generator](https://github.com/FENRlR/MB-iSTFT-VITS2/blob/17593f65ae3cfa99fa584c1e4e1d5723e2a4d97d/models.py#L898) does not use subbands, nor the pqmf. They are for the mb and ms variants.
